AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.001

#Last Used For Model 6
#AUGMENTATION: True
#IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
#BATCH_SIZE: 32
#INCLUDE_TOP: False
#EPOCHS: 2
#CLASSES: 2
#WEIGHTS: imagenet
#LEARNING_RATE: 0.001
